services:
  registry:
    image: registry:2
    restart: always
    container_name: registry
    environment:
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/registry.passwd
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry
    volumes:
      - ./data:/var/lib/registry
      - ./auth:/auth
    ports:
      - ${REGISTRY_PORT}:5000
    networks:
      - registry-net

  registry-ui:
    image: joxit/docker-registry-ui:latest
    restart: always
    container_name: registry-ui
    environment:
      - REGISTRY_TITLE=${REGISTRY_TITLE}
      - REGISTRY_URL=${REGISTRY_UI_REGISTRY_URL}
      - SINGLE_REGISTRY=true
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - REGISTRY_URL=${NGINX_PROXY_PASS_URL}
    ports:
      - ${REGISTRY_UI_PORT}:80
    depends_on:
      - registry
    networks:
      - registry-net

networks:
  registry-net:
