version: '3'

services:
  registry-ui:
    image: joxit/docker-registry-ui:main
    restart: always
    ports:
      - ${UI_PORT}:80
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Docker Registry UI
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_PASS_URL=http://my_registry:${PORT}
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=false
      - CATALOG_ELEMENTS_LIMIT=1000
    container_name: registry-ui

  registry:
    image: registry:latest
    container_name: my_registry
    ports:
      - "${PORT}:5000"
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_HTTP_HOST: https://registry.${REGISTRY_DOMAIN}
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - ./registry-data:/var/lib/registry
      - ./auth:/auth

volumes:
  registry-data:
  auth:
